libminha: 
	#gcc -fPIC -shared -o libmine.so *.c
	gcc -o ../ls ls.c
	gcc -o ../help help.c
	gcc -o ../cd cd.c
	gcc -o ../adduser adduser.c
	gcc -o ../deluser deluser.c
	gcc -o ../pwd pwd.c
	gcc -o ../printf printf.c
	gcc -o ../time time.c
	gcc -o ../whoami whoami.c
	gcc -o ../userdel userdel.c
	gcc -o ../useradd useradd.c


	
